# Default values for uffizzi-cluster-operator
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: docker.io/uffizzi/uffizzi-cluster-operator
  tag: v0.0.5

# `flux` dependency values
flux:
  helmController:
    enabled: true
    metrics:
      enabled: false
  sourceController:
    enabled: true
    metrics:
      enabled: false
  kustomizeController:
    enabled: false
  notificationController:
    enabled: false
  imageAutomationController:
    enabled: false
  imageReflectorController:
    enabled: false

cert-manager: # dependency
  enabled: true
  installCRDs: true
