apiVersion: v1
kind: Service
metadata:
  labels: {{ include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/part-of: uffizzi
  name: {{ include "common.names.fullname" . | trunc 55 | trimSuffix "-" }}-metrics
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
