# permissions for end users to edit UffizziClusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: UffizziCluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: uffizzi-cluster-operator
    app.kubernetes.io/part-of: uffizzi-cluster-operator
    app.kubernetes.io/managed-by: kustomize
  name: UffizziCluster-editor-role
rules:
- apiGroups:
  - uffizzi.com
  resources:
  - UffizziClusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - uffizzi.com
  resources:
  - UffizziClusters/status
  verbs:
  - get
