spec:
  template:
    spec:
      tolerations:
        - key: "sandbox.gke.io/runtime"
          operator: "Equal"
          value: "gvisor"
          effect: "NoSchedule"
      nodeSelector:
        sandbox.gke.io/runtime: "gvisor"
