kind: UffizziCluster
apiVersion: uffizzi.com/v1alpha1
metadata:
  name: helm-basic
spec:
  ingress:
    class: "nginx"
    host: deleteme2023.uffizzi.cloud
    certManagerTLSEnabled: true
    services:
    - name: kubernetes-dashboard
      namespace: kubernetes-dashboard
      port: 443
      ingressAnnotations:
        nginx.ingress.kubernetes.io/auth-url: "https://auth.uc.deleteme2023.uffizzi.cloud/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://auth.uc.deleteme2023.uffizzi.cloud/oauth2/start?rd=https%3A%2F%2F$host$request_uri"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        ingress.kubernetes.io/force-ssl-redirect: "true"
        ingress.kubernetes.io/proxy-body-size: "1024m"
        nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
        nginx.ingress.kubernetes.io/secure-backends: "true"
        cert-manager.io/cluster-issuer: "my-uffizzi-letsencrypt"
  ttl: 1h
  helm:
  - chart:
      name: kubernetes-dashboard
      repo: https://kubernetes.github.io/dashboard/
    release:
      name: kubernetes-dashboard
      namespace: kubernetes-dashboard
    values: |
      extraArgs:
        - --enable-skip-login
        - --enable-insecure-login
        - --system-banner="This is a Uffizzi Virtual Cluster"
      rbac:
        create: true
        clusterReadOnlyRole: true
  - chart:
      name: jenkins
      repo: https://charts.jenkins.io
    release:
      name: jenkins
      namespace: default

