kind: UffizziCluster
apiVersion: uffizzi.com/v1alpha1
metadata:
  name: i132
spec:
  distro: k3s
  apiServer:
    image: "rancher/k3s:v1.25.14-k3s1"
  ingress:
    host: testns.uclusters.app.qa-gke.uffizzi.com
  resourceQuota:
    enabled: false
  limitRange:
    enabled: false

