kind: UffizziCluster
apiVersion: uffizzi.com/v1alpha1
metadata:
  name: nodeselector-tolerations
spec:
  nodeSelector:
    testkey: testvalue
  tolerations:
  - key: "testkey"
    operator: "Equal"
    value: "testvalue"
    effect: "NoSchedule"

