kind: UffizziCluster
apiVersion: uffizzi.com/v1alpha1
metadata:
  name: i11
spec:
  ingress:
    host: test.app.qa-gke.uffizzi.com
  resourceQuota:
    enabled: false
  limitRange:
    enabled: false

