kind: UffizziCluster
apiVersion: uffizzi.com/v1alpha1
metadata:
  name: i27
spec:
  resourceQuota:
    enabled: false
  limitRange:
    enabled: false
  ingress:
    host: app.qa-gke.uffizzi.com
  manifests: |
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: ingress-1
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
    spec:
      rules:
        - http:
            paths:
              - path: /testpath
                pathType: Prefix
                backend:
                  service:
                    name: test
                    port:
                      number: 80
    ---
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: ingress-2
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
    spec:
      rules:
        - host: whathostmost
          http:
            paths:
              - path: /testpath
                pathType: Prefix
                backend:
                  service:
                    name: test
                    port:
                      number: 80
