kind: UffizziCluster
apiVersion: uffizzi.com/v1alpha1
metadata:
  name: i32
spec:
  apiServer:
    image: "rancher/k3s:v1.27.3-k3s1"
  ingress:
    host: app.qa-gke.uffizzi.com
  resourceQuota:
    enabled: false
  limitRange:
    enabled: false

