kind: UffizziCluster
apiVersion: uffizzi.com/v1alpha1
metadata:
  name: testnode
spec:
#  ingress:
#    class: "nginx"
#    host: deleteme2023.uffizzi.cloud
#    services:
#      - name: test-node-svc
#        namespace: test-node
#        port: 8080
#        ingressAnnotations:
#          nginx.ingress.kubernetes.io/auth-url: "https://auth.uc.deleteme2023.uffizzi.cloud/oauth2/auth"
#          nginx.ingress.kubernetes.io/auth-signin: "https://auth.uc.deleteme2023.uffizzi.cloud/oauth2/start?rd=https%3A%2F%2F$host$request_uri"
#          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
#          nginx.ingress.kubernetes.io/ssl-redirect: "true"
#          ingress.kubernetes.io/force-ssl-redirect: "true"
#          ingress.kubernetes.io/proxy-body-size: "1024m"
#          nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
#          nginx.ingress.kubernetes.io/secure-backends: "true"
#          cert-manager.io/cluster-issuer: "my-uffizzi-letsencrypt"
#        certManagerTLSEnabled: true
#  ttl: 1h
#  components: 'helm'
  helm:
    - chart:
        name: test-node
        repo: https://zipofar.github.io/test_node
      release:
        name: test-node
        namespace: test-node
      values: |
        image: dbpterraform2/test-node-zipofar:latest
        app_port: 8080