kind: UffizziCluster
apiVersion: uffizzi.com/v1alpha1
metadata:
  name: sample
spec:
  ingress:
    class: "nginx"
    host: deleteme2023.uffizzi.cloud
    services:
    - name: kubernetes-dashboard
      namespace: kubernetes-dashboard
      port: 443
    - name: testkube-dashboard
      namespace: testkube
      port: 8080
  ttl: 1h
  components: 'helm'
  helm:
  - chart:
      name: kubernetes-dashboard
      repo: https://kubernetes.github.io/dashboard/
    release:
      name: kubernetes-dashboard
      namespace: kubernetes-dashboard
  - chart:
      name: testkube
      repo: https://kubeshop.github.io/helm-charts
    values: |-
      installCRDs: true
    release:
      name: testkube
      namespace: testkube
