name: Test - E2E - Performance # e2e tests running against a k8s cluster

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  build-operator:
    uses: ./.github/workflows/build-operator.yaml
    name: Build Operator Image
    secrets: inherit

  minikube:
    needs:
    - build-operator
    name: Run Performance Tests on Minikube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Helm Values Artifact
        uses: actions/download-artifact@v3
        with:
          name: helm-values

      - name: Start Minikube
        run: minikube start --addons default-storageclass,storage-provisioner --driver=docker

      - name: Install Uffizzi Cluster Operator
        id: prev
        run: |
          helm dep update ./chart
          helm upgrade --install --wait pr-${{ github.event.pull_request.number }} \
          ./chart -f helm-values.yaml

      # Identify comment to be updated
      - name: Find comment for Performance Overview
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Performance Overview
          direction: last

      # Create/Update comment with action deployment status
      - name: Create or Update Comment with Performance Overview
        id: notification
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Performance Overview

            :gear: Running performance tests on Minikube

          edit-mode: replace

      - name: Time taken to create UffizziClusters with 5 workers
        run: |
          # File where the JSON data will be stored
          JSON_FILE="data.json"
          
          # Ensure the file exists and initialize it as an empty array if not
          if [ ! -f "$JSON_FILE" ]; then
          echo '[]' > "$JSON_FILE"
          fi
          
          time=$(bash hack/e2e/perf/01-multicluster.sh)
          jq --argjson newEntry "{\"workers\": 5, \"time\": $time}" '. += [$newEntry]' "$JSON_FILE" > "tmp.$$" && mv "tmp.$$" "$JSON_FILE"
          
          cat data.json

      - name: Set concurrent to 10
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.concurrent = "10"' helm-values.yaml

      - name: Time taken to create UffizziClusters with 10 workers
        run: |
          JSON_FILE="data.json"
          helm upgrade --install --wait pr-${{ github.event.pull_request.number }} \
          ./chart -f helm-values.yaml
          time=$(bash hack/e2e/perf/01-multicluster.sh)
          jq --argjson newEntry "{\"workers\": 10, \"time\": $time}" '. += [$newEntry]' "$JSON_FILE" > "tmp.$$" && mv "tmp.$$" "$JSON_FILE"
          
          cat data.json

      - name: Set concurrent to 15
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.concurrent = "15"' helm-values.yaml

      - name: Time taken to create UffizziClusters with 15 workers
        run: |
          JSON_FILE="data.json"
          helm upgrade --install --wait pr-${{ github.event.pull_request.number }} \
          ./chart -f helm-values.yaml
          time=$(bash hack/e2e/perf/01-multicluster.sh)
          jq --argjson newEntry "{\"workers\": 15, \"time\": $time}" '. += [$newEntry]' "$JSON_FILE" > "tmp.$$" && mv "tmp.$$" "$JSON_FILE"
          
          cat data.json

      - name: Set concurrent to 20
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.concurrent = "20"' helm-values.yaml

      - name: Time taken to create UffizziClusters with 20 workers
        run: |
          JSON_FILE="data.json"
          helm upgrade --install --wait pr-${{ github.event.pull_request.number }} \
          ./chart -f helm-values.yaml
          time=$(bash hack/e2e/perf/01-multicluster.sh)
          jq --argjson newEntry "{\"workers\": 20, \"time\": $time}" '. += [$newEntry]' "$JSON_FILE" > "tmp.$$" && mv "tmp.$$" "$JSON_FILE"
          
          cat data.json

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib

      - name: Create Graph
        run: python hack/e2e/perf/viz/generate_graph.py

      - name: Upload Graph as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: performance-graph
          path: ./performance_graph.png

      - name: Update Comment with Performance Overview
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.notification.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ##  Performance Overview

            ![Graph](./performance_graph.png)
          edit-mode: replace
