name: Unit Tests and Coverage

on:
  pull_request:
    branches: [ main ]

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: ^1.19
      - name: Lint Helm Chart
        run: |
          (cd ./chart && helm dep update .)
          helm lint ./chart --with-subcharts
      - name: Test
        run: go test -coverprofile=coverage.txt -covermode=atomic -v ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
